# Generated by Django 5.0.6 on 2024-06-27 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_senha'),
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_agendada', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('ponto_coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point.pontocoleta')),
            ],
        ),
    ]
