# Generated by Django 5.0.6 on 2024-07-10 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_catalogoroupas_unique_together'),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentodoacao',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogoroupas'),
        ),
        migrations.AddField(
            model_name='agendamentodoacao',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamentodoacao',
            name='data_hora_agendada',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
