# Generated by Django 5.0.6 on 2024-07-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_agendamentodoacao_data_hora_agendada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentodoacao',
            name='data_hora_agendada',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
