# Generated by Django 5.0.6 on 2024-06-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_doador', models.BooleanField(default=False)),
                ('is_beneficiario', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('senha', models.IntegerField()),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
