# Generated by Django 5.0.6 on 2024-06-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
