# Generated by Django 5.0.6 on 2024-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoRoupas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tamanho', models.CharField(blank=True, max_length=10, null=True)),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('bom', 'Bom'), ('razoavel', 'Razoável')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
