# Generated by Django 5.0.6 on 2024-06-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_catalogoroupas_descricao_catalogoroupas_tipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogoroupas',
            unique_together={('tipo', 'tamanho', 'condicao')},
        ),
    ]
