# Generated by Django 5.0.6 on 2024-06-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalogoroupas_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogoroupas',
            unique_together=set(),
        ),
    ]
